DWAPlannerROS:
  max_vel_x: 0.1
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 0.8
  min_vel_theta: -0.5
  acc_lim_x: 1.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  yaw_goal_tolerance: 0.01
  xy_goal_tolerance: 0.1
  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vy_samples: 1
  vtheta_samples: 20
  path_distance_bias: 90.0
  goal_distance_bias: 70.0
  occdist_scale: 0.5
  forward_point_distance: 0.125
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: odom
  oscillation_reset_dist: 0.05