local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  plugins:
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
  obstacles:
    observation_sources: scan
    scan:
      sensor_frame: lidar_Link
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      obstacle_range: 5.5
      raytrace_range: 6.0